---
title: "awardFindR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{awardFindR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`awardFindR()` is meant to be the top-level function for interacting with grant databases.

The simplest way to generate the dataset is to run the function with the default keywords set, as follows
```
grants <- awardFindR("data/keywords.csv")
```

This pulls data from all supported databases, querying the results for each term in `data/keywords.csv` over the past two years. All these parameters are modifiable. For example, if we only wanted to search a few of the supported databases, we could run 
```
nsf <- awardFindR(keywords="data/keywords.csv", sources="nsf")

results <- awardFindR(keywords="data/keywords.csv", sources=c("nsf", "nih"))
```

If we wanted to test different keywords, that parameter either accepts a file name or a character vector of keywords. For example:
```
new_terms <- awardFindR(keywords="qualitative data")

new_terms <- awardFindR(keywords=c("qualitative data", "ethnography"))

new terms <- awardFindR(keywords="new_terms.csv")
```
If you specify a .csv file, it should be a list of keywords, one string per line.

We can change the date limitations on our search as well, like so
```
last_five_years <- awardFindR("keywords", sources="nih", from_date="2015-01-01", to_date="2020-01-01")

last_year <- awardFindR("keywords", sources="nih", from_date="2019-01-01", to_date="2020-01-01")
```
We can also omit one of these terms. The `from` parameter defaults to January 1 2019, while the `to` parameter defaults to the current date. If we wanted to search all databases for all keywords from 2015 to the current date, for example, we would run
```
results <- awardFindR("keywords", sources="nih", from_date="2015-01-01")
```

Throughout this package, date parameters should be able to be coerced into `Date()` objects. This means dates should adhere to a "yyyy-mm-dd" format if specificed as strings.
